[boot]
method = "qemu-direct"

[build]
strip_elf = false

[run]
boot.kcmd_args = [
    "SHELL=/bin/sh",
    "LOGNAME=root",
    "HOME=/",
    "USER=root",
    "PATH=/bin",
    "init=/usr/bin/busybox",
]
#boot.init_args = ["sh", "-l"]
boot.init_args = ["echo", "Hello, World"]
#boot.initramfs = "regression/build/initramfs.cpio.gz"
boot.initramfs = "../initramfs.cpio.gz"

[qemu]
args = """\
    -cpu rv64,zba=true,zbb=true \
    -machine virt \
    -m 2G \
    --no-reboot \
    -nographic \
    -display none \
    -serial chardev:mux \
    -monitor chardev:mux \
    -chardev stdio,id=mux,mux=on,signal=off,logfile=qemu.log \
    -drive if=none,format=raw,id=x0,file=./regression/build/ext2.img \
    -drive if=none,format=raw,id=x1,file=./regression/build/exfat.img \
    -device virtio-blk-device,drive=x0 \
    -device virtio-keyboard-device \
    -device virtio-serial-device \
    -device virtconsole,chardev=mux \
"""
